name: Create torrent using py3createtorrent
on:
  push:
    paths:
      - ".github/workflows/py3createtorrent.yml"
      
env:
  name: Firefox Setup 84.0.2
  comment: Firefox Setup 84.0.2 by torrent-webseed-creator
  url: https://srv-store5.gofile.io/download/lAfnk4/lazypurpleleaf%20videos.zip
  file_name: "Firefox Setup 84.0.2.exe"
  piece_size: 0 # 0 for automatic calculation, or use the recommended piece size on the README.md file
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install py3createtorrent
        run: sudo pip3 install py3createtorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using py3createtorrent
        run: py3createtorrent -p $piece_size -c "$comment" -o "${name}.torrent" --webseed "$url" "$file_name" # Tested on 1.0.0b2
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
